import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import authRoutes from "./auth.js";
import marketplaceRoutes from "./marketplaces.js";
import affiliateAccountRoutes from "./affiliate-accounts.js";
import aiRoutes from "./ai.js";
import brandRoutes from "./brands.js";
import offerRoutes from "./offers.js";
import couponRoutes from "./coupons.js";
import categoryRoutes from "./categories.js";
import productRoutes from "./products.js";
import messageTemplateRoutes from "./message-templates.js";
import campaignRoutes from "./campaigns.js";
import scheduledPostRoutes from "./scheduled-posts.js";
import channelRoutes from "./channels.js";
import intelligenceRoutes from "./intelligence.js";
import priceHistoryRoutes from "./price-history.js";
import reportRoutes from "./reports.js";
import seoRoutes from "./seo.js";
import userRoutes from "./users.js";
import whatsappRoutes from "./whatsapp.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/marketplaces", requireAuth, marketplaceRoutes);
router.use("/affiliate-accounts", requireAuth, affiliateAccountRoutes);
router.use("/ai", requireAuth, aiRoutes);
router.use("/brands", requireAuth, brandRoutes);
router.use("/categories", requireAuth, categoryRoutes);
router.use("/coupons", requireAuth, couponRoutes);
router.use("/products", requireAuth, productRoutes);
router.use("/offers", requireAuth, offerRoutes);
router.use("/intelligence", requireAuth, intelligenceRoutes);
router.use("/message-templates", requireAuth, messageTemplateRoutes);
router.use("/campaigns", requireAuth, campaignRoutes);
router.use("/scheduled-posts", requireAuth, scheduledPostRoutes);
router.use("/channels", requireAuth, channelRoutes);
router.use("/price-history", requireAuth, priceHistoryRoutes);
router.use("/reports", requireAuth, reportRoutes);
router.use("/seo", requireAuth, seoRoutes);
router.use("/users", requireAuth, userRoutes);
router.use("/whatsapp", requireAuth, whatsappRoutes);

export default router;
