FROM wppconnect/server-cli:latest

COPY config.js /usr/src/wpp-server/dist/config.js
COPY redis-db.js /usr/src/wpp-server/dist/util/db/redis/db.js
COPY redis-token-store.js /usr/src/wpp-server/dist/util/tokenStore/redisTokenStory.js
